const excusas = [ 
"Me quedé sin batería en el móvil y no sonó la alarma.",
"Había un tráfico horroroso por un accidente.",
"Se me olvidaron las llaves dentro de casa y tuve que llamar al cerrajero.",
"Mi perro se puso malo de repente y tuve que llevarlo al veterinario.",
"Me equivoqué de día en la agenda.",
"Se fue la luz en todo el barrio.",
"Internet no me funcionaba y no pude avisar.",
"Me sentó mal la cena de ayer y he pasado una noche fatal.",
"El tren se quedó parado en mitad del túnel.",
"No encontraba sitio para aparcar y di vueltas durante media hora.",
"Me surgió una emergencia familiar de última hora.",
"Pensé que habíamos quedado a otra hora.",
"Se me rompió el tacón del zapato justo al salir de casa.",
"Tuve que ayudar a una vecina anciana que se quedó encerrada.",
"Me quedé encerrado en el ascensor.",
"El GPS me mandó a una dirección que no era.",
"Me lié con una llamada de trabajo que no podía cortar.",
"Perdí el autobús por diez segundos.",
"Se me inundó la cocina por una fuga en el fregadero.",
"Mi coche no arrancaba, creo que es la batería.",
"Me dio un ataque de migraña repentino.",
"No me llegó el correo de confirmación.",
"Se me actualizó el ordenador justo cuando iba a empezar.",
"Tuve que ir a recoger a mi hermano porque se quedó tirado.",
"Me picó una abeja y soy un poco alérgico.",
"No encontraba la cartera por ninguna parte.",
"Había una manifestación cortando las calles principales.",
"El despertador no sonó porque se desconfiguró.",
"Me quedé sin gasolina a mitad de camino.",
"Me dio un tirón en la espalda al agacharme.",
"Había mucha cola en la farmacia por una urgencia.",
"Me confundí de lugar de encuentro.",
"Se me rompió la tubería general del edificio.",
"Me entró algo en el ojo y no podía ver para conducir.",
"Me llamaron del colegio de mi hijo porque se encontraba mal.",
"Me quedé dormido en el sofá sin querer.",
"Se me cayó el café encima de la ropa y tuve que cambiarme.",
"El metro iba con un retraso de 20 minutos.",
"No escuché el timbre porque estaba en la ducha.",
"Me quedé sin datos en el móvil y me perdí.",
"Había obras en mi calle y no dejaban salir los coches.",
"Me dio un bajón de tensión.",
"Se me olvidó por completo, tengo mil cosas en la cabeza.",
"Tuve que llevar a mi madre a una revisión médica de urgencia.",
"Me robaron la bicicleta.",
"La aplicación de mapas se quedó colgada.",
"Me puse a leer y perdí la noción del tiempo.",
"Un camión de basura bloqueó mi calle estrecha.",
"Me quemé con la plancha terminando de arreglarme.",
"Me sentía muy mareado esta mañana.",
"Se me perdió el gato y estuve buscándolo por el jardín.",
"Me llamaron para una encuesta telefónica infinita.",
"Me quedé sin llaves del coche.",
"Había una huelga de transportes que no conocía.",
"Me dio una alergia terrible por el polen.",
"Se me rompió la cremallera del pantalón justo antes de salir.",
"El vecino me paró para contarme un problema serio.",
"Me equivoqué al anotar la cita en el calendario digital.",
"Tenía el móvil en silencio por una reunión anterior.",
"Se me pinchó una rueda del coche.",
"Me quedé bloqueado pensando en un problema del trabajo.",
"Me sentí indispuesto de repente.",
"Tuve un problema con el banco y tuve que ir en persona.",
"Había mucha niebla y no se podía circular rápido.",
"Me confundí de semana.",
"Perdí el ticket del parking y tardé en salir.",
"Me distraje ayudando a alguien por la calle.",
"Se me olvidó cargar el coche eléctrico.",
"Me dio un calambre muy fuerte en la pierna.",
"Pensé que la reunión era por videollamada.",
]

const excusaAletoria = excusas[Math.floor(Math.random()*70)];

document.getElementById("excu").innerHTML = excusaAletoria;